webtalk_init -webtalk_dir C:/Users/SHC/vivado/aes_engine_wrapper/aes_engine_wrapper.sim/sim_1/impl/func/xsim/xsim.dir/tb_aes_wrapper_func_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Aug  8 19:07:06 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8c8a7e15-599f-401a-bfc2-e6238b2ff962" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b7faabb87e4440d4a3acabc874bbf1c5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "8376284 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "8.17_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "116020_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2567439769 -regid "" -xml C:/Users/SHC/vivado/aes_engine_wrapper/aes_engine_wrapper.sim/sim_1/impl/func/xsim/xsim.dir/tb_aes_wrapper_func_impl/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/SHC/vivado/aes_engine_wrapper/aes_engine_wrapper.sim/sim_1/impl/func/xsim/xsim.dir/tb_aes_wrapper_func_impl/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/SHC/vivado/aes_engine_wrapper/aes_engine_wrapper.sim/sim_1/impl/func/xsim/xsim.dir/tb_aes_wrapper_func_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
